### ISSUE TITLE
[INTEGRAÇÃO] Integrar ENDPOINT para indentificar e-mail do Mentor

### ISSUE THREAD

**Issue by akirashimazu** [SouJunior/mentores-frontend#172]

**Comment by hudson-viana** [comment]
Movido de 'Em desenvolvimento' para 'ready' pois não está na sprint atual.

**Comment by hudson-viana** [comment]
Movido para 'finalizado', pois não temos no momento uma coluna 'arquivado'. Task movida para finalizado pois essa task era um planejamento da equipe passada a qual não teve aplicabilidade na estratégia de desenvolvimento da equipe atual.

**Comment by andremomesso** [comment]
Estou encerrando esta demanda, pois a mesma já está em Produção.
