### ISSUE TITLE
[2/2] Primeiro login - Finalização

### ISSUE THREAD

**Issue by raiane-oliveira** [SouJunior/mentores-frontend#182]

**Comment by raiane-oliveira** [comment]
Finalização do Primeiro login.
Redirecionamento para a página Home com o modal de se conectar ao calendly. 


![Image](https://github.com/SouJunior/mentores-frontend/assets/100815627/fafb6e01-6203-44fd-892a-09df7de03f4e)

**Comment by andremomesso** [comment]
Estou encerrando esta demanda, pois a mesma já está em Produção.
