### ISSUE TITLE
[Login Mentor] Não permitir que o usuário faça login de novo depois de logado

### ISSUE THREAD

**Issue by raiane-oliveira** [SouJunior/mentores-frontend#184]
Referente a US https://github.com/orgs/SouJunior/projects/11/views/1?pane=issue&itemId=11853605

Não permitir que o usuário acesse a rota /login e /cadastro depois que já estiver logado no site.

**Comment by andremomesso** [comment]
Estou encerrando esta demanda, pois a mesma já está em Produção.
