### ISSUE TITLE
[Seção Mentores] - Delimitar um limite fixo de áreas para aparecer no card

### ISSUE THREAD

**Issue by raiane-oliveira** [SouJunior/mentores-frontend#186]
Delimitar um tamanho fixo de 3 áreas para aparecer no card de mentores, com o intuito de não quebrar o layout/

![image](https://github.com/SouJunior/mentores-frontend/assets/100815627/41ac0ffb-7b9c-42a9-8140-8b90b985e1ac)

**Comment by andremomesso** [comment]
Estou encerrando esta demanda, pois a mesma já está em Produção.
