### ISSUE TITLE
Bug que quando o usuário não coloca para manter conectado ele não consegue acessar o perfil

### ISSUE THREAD

**Issue by wendesongomes** [SouJunior/mentores-frontend#204]
Quando o usuário não coloca para manter conectado, não salva o cookie essencial para verificar se o usuario esta logado para acessar o seu perfil

![image](https://github.com/SouJunior/mentores-frontend/assets/82889172/5cbc5756-05d7-4573-b790-ebefabf2f183)

**Comment by hudson-viana** [comment]
- PR que soluciona esse bug: [PR-205](https://github.com/SouJunior/mentores-frontend/pull/205) - feito pelo Wendeson.
- US relacionadas a esse assunto de "Minha conta" e "área logada": ( [US-6](https://github.com/SouJunior/products/issues/6), [US-136](https://github.com/SouJunior/products/issues/136), [US-352](https://github.com/SouJunior/products/issues/352) )
