### ISSUE TITLE
Integração do Calendly no site

### ISSUE THREAD

**Issue by hudson-viana** [SouJunior/mentores-frontend#207]
Objetivo da task: atender os critérios de aceite do [US-426](https://github.com/SouJunior/products/issues/426).

**Comment by hudson-viana** [comment]
Task finalizada, fiz desenvolvimento nesse PR: https://github.com/SouJunior/mentores-frontend/pull/213

**Comment by andremomesso** [comment]
Estou encerrando esta demanda, pois a mesma já está em Produção.
