### ISSUE TITLE
No mobile não está aparecendo a sessão "Minha Conta"

### ISSUE THREAD

**Issue by hudson-viana** [SouJunior/mentores-frontend#208]
- Objetivo do card: corrigir o bug: No mobile não está aparecendo a sessão "Minha Conta"
- US relacionadas a esse assunto de "Minha conta" e "área logada": ( [US-6](https://github.com/SouJunior/products/issues/6), [US-136](https://github.com/SouJunior/products/issues/136), [US-352](https://github.com/SouJunior/products/issues/352) )

**Comment by arieviloanelym** [comment]
Nome do Teste: No mobile não está aparecendo a sessão "Minha Conta"

Data de Execução: 21/07/2025

Executor: @arieviloanelym 

Ambiente: DevTools

Versão do navegador:  Google Chrome

Resultado esperado: No mobile deve constar a sessão "Minha Conta"

Resultado obtido: O sistema se comportou conforme o esperado.

<img width="387" height="796" alt="Image" src="https://github.com/user-attachments/assets/86016d78-6ad7-46c5-9575-2ab83c5c1ec2" />

Teste passou 

@AnselmoQA

**Comment by jamgrungez** [comment]
Nome do Teste: No mobile não está aparecendo a sessão "Minha Conta"

Data de Execução: 27/5/26

Executor: @jamgrungez 

Ambiente: DevTools

Versão do navegador: Opera

Resultado esperado: No mobile deve constar a sessão "Minha Conta"

Resultado obtido: O sistema se comportou conforme o esperado, porém a página não está mobile-friendly, não foi testado em prod pois o cadastro como mentor não funcionou (reportado em card de bugs no backlog)
<img width="522" height="573" alt="Image" src="https://github.com/user-attachments/assets/ad42889e-b518-4370-b1c5-ab6c9aaf0317" />

**Comment by andremomesso** [comment]
Demanda já está em produção.
