### ISSUE TITLE
[Mentor] Realizar login

### ISSUE THREAD

**Issue by piantino** [SouJunior/mentores-frontend#3]
US - https://github.com/SouJunior/products/issues/4

**Comment by caiquefonseca** [comment]
@Patrickresplandes precisa do EndPoint e da API para fazer a requisição, para ver se está buscando os dados. @wandersonDeve você pode ajudar?

**Comment by Patrickresplandes** [comment]
Irei testar as API agora mesmo.

**Comment by Patrickresplandes** [comment]
Api testada e fazendo requisições ok.

**Comment by jamgrungez** [comment]
não consigo validar

**Comment by andremomesso** [comment]
Estou encerrando esta demanda, pois a mesma já está em Produção.
