### ISSUE TITLE
Implementar Slider de mentores

### ISSUE THREAD

**Issue by abelardojr0** [SouJunior/mentores-frontend#80]
Criar componente de slider onde é possível controlar a passagem dos cards

![Image](https://user-images.githubusercontent.com/97140028/245645406-1883dcdb-7752-4778-8324-f1f02f0f4875.png)

**Requerimentos**

- [x]  Desenvolver de acordo com layout acima
- [ ]  Habilitar controles de rolagem para esquerda e para direita, desabilitando-os quando chegar ao limite

**Comment by luizpbello** [comment]
@abelardojr0 . Da uma olhada no FIGMA e como ficou o resultado. Estão questionando a diferença de layouyt

**Comment by luizpbello** [comment]
Já fiz os ajustes com a [PR#102](https://github.com/SouJunior/mentores-frontend/pull/102)
